dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.3

solidity:
  import_remapping:
    - "@openzeppelin=OpenZeppelin/v4.9.3"

# compiler:
#   solc:
#     remappings:
#       #- '@openzeppelin=/home/papas/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.8.1'     #Linux path
#       - '@openzeppelin=C:\Users\KOSTAS\.brownie\packages\OpenZeppelin\openzeppelin-contracts@4.8.1' #Windows path
